version: '3.1'

services:
  php:
    container_name: untitled_app_php
    build: ./docker
    volumes:
      - .:/var/www
    links:
      - database
    environment:
      TZ: Asia/Tokyo

  nginx:
    image: nginx:latest
    container_name: untitled_app_nginx
    ports:
      - 83:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    environment:
      TZ: Asia/Tokyo

  database:
    image: mysql:latest
    container_name: untitled_app_mysqld
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/db.cnf:/etc/mysql/conf.d/db.cnf
    ports:
      - 3337:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: untitled_app
      MYSQL_USER: untitled_user
      MYSQL_PASSWORD: secret
